env:
  es2022: true
  node: true
  jest/globals: true
parserOptions:
  ecmaVersion: 2022
  ecmaFeatures:
    impliedStrict: true
  sourceType: module
extends:
  - 'eslint:recommended'
  - prettier
plugins:
  - jest
rules:
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - error
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^debug$
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
ignorePatterns:
  - migrations/*.js
