import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";

import { Skill } from "../Models/Skill";

const skills = [
  [".NET Framework", ".NET Framework"],
  ["Agile Methodologies", "アジャイル手法"],
  ["Amazon Web Services (AWS)", "Amazon Web Services (AWS)"],
  ["Android", "Android"],
  ["AngularJS", "AngularJS"],
  ["ArcGIS", "ArcGIS"],
  ["AWS Lambda", "AWS Lambda"],
  ["Bash", "Bash"],
  ["C", "C"],
  ["C#", "C#"],
  ["C++", "C++"],
  ["CSS", "CSS"],
  ["Django", "Django"],
  ["Dreamweaver", "Dreamweaver"],
  ["Eclipse", "Eclipse"],
  ["Git", "Git"],
  ["Google Analytics", "Google アナリティクス"],
  ["Google Cloud Platform (GCP)", "Google Cloud Platform (GCP)"],
  ["Hadoop", "Hadoop"],
  ["HTML", "HTML"],
  ["Java", "Java"],
  ["JavaScript", "JavaScript"],
  ["JQuery", "JQuery"],
  ["JSON", "JSON"],
  ["Kotlin", "Kotlin"],
  ["Machine Learning", "機械学習"],
  ["MATLAB", "MATLAB"],
  ["Maven", "Maven"],
  ["Microsoft T-SQL", "Microsoft T-SQL"],
  ["MongoDB", "MongoDB"],
  ["Node.js", "Node.js"],
  ["NoSQL", "NoSQL"],
  ["Objective-C", "Objective-C"],
  ["Object-Oriented Programming", "オブジェクト指向プログラミング"],
  ["PHP", "PHP"],
  ["Python", "Python"],
  ["R Programming", "R プログラミング"],
  ["React.JS", "React.JS"],
  ["REST API", "REST API"],
  ["Rhino 3D", "Rhino 3D"],
  ["Ruby-on-Rails", "Ruby-on-Rails"],
  ["Scala", "Scala"],
  ["Search Engine Optimization (SEO)", "検索エンジン最適化(SEO)"],
  ["Spring Framework", "Spring Framework"],
  ["Swift", "Swift"],
  ["Unity", "Unity"],
  ["Visual Basic for Applications (VBA)", "Sustainable Development"],
  ["Windows Server", "Windows Server"],
  ["Wordpress", "Wordpress"],
  ["XML", "XML"],
  ["Adobe Acrobat", "Adobe Acrobat"],
  ["Google Ads", "Google 広告"],
  ["Microsoft Access", "Microsoft Access"],
  ["Microsoft Azure", "Microsoft Azure"],
  ["Microsoft Excel", "Microsoft Excel"],
  ["Microsoft Outlook", "Microsoft Outlook"],
  ["Microsoft Power BI", "Microsoft Power BI"],
  ["Microsoft PowerPoint", "Microsoft PowerPoint"],
  ["Microsoft Project", "Microsoft Project"],
  ["Microsoft SharePoint", "Microsoft SharePoint"],
  ["Microsoft Visio", "Microsoft Visio"],
  ["Microsoft Word", "Microsoft Word"],
  ["QuickBooks", "QuickBooks"],
  ["Adobe Animate", "Adobe Animate"],
  ["Adobe Illustrator", "Adobe Illustrator"],
  ["Adobe Lightroom", "Adobe Lightroom"],
  ["Adobe Photoshop", "Adobe Photoshop"],
  ["Adobe Premier Pro", "Adobe Premier Pro"],
  ["Adobe XD", "Adobe XD"],
  ["After Effects", "After Effects"],
  ["AutoCAD", "AutoCAD"],
  ["Autodesk Fusion 360", "Autodesk Fusion 360"],
  ["Autodesk Inventor", "Autodesk Inventor"],
  ["Avid Media Composer", "Avid Media Composer"],
  ["Final Cut Pro", "Final Cut Pro"],
  ["iMovie", "iMovie"],
  ["InDesign", "InDesign"],
  ["Keynote", "Keynote"],
  ["Logic Pro", "Logic Pro"],
  ["Pro Tools", "Pro Tools"],
  ["Revit", "Revit"],
  ["SketchUp", "SketchUp"],
  ["SOLIDWORKS", "SOLIDWORKS"],
  ["Dart", "Dart"],
  ["React Native", "React Native"],
  ["Flutter", "Flutter"],
  ["Programming", "プログラミング"],
  ["Algorithms", "アルゴリズム"],
  ["Artificial Intelligence (AI)", "人工知能(AI)"],
  ["Data Science", "データサイエンス"],
  ["Software Engineering", "ソフトウェア工学"],
  ["Data Mining", "データマイニング"],
  ["Shell Scripting", "シェルスクリプト"],
  ["Software Development", "ソフトウェア開発"],
  ["Computer Science", "コンピュータサイエンス"],
  ["Ruby", "Ruby"],
  ["Linux", "Linux"],
  ["Natural Language Processing", "自然言語処理"],
  ["Apache Spark", "Apache Spark"],
  ["Apache Pig", "Apache Pig"],
  ["Open CV", "Open CV"],
  ["Unsupervised Learning", "教師なし学習(Unsupervised Learning)"],
  ["Collaborative Filtering", "協調フィルタリング"],
  ["Google Ad Manager", "Google Ad Manager"],
  ["Google AdSense", "Google AdSense"],
  ["Google AdMob", "Google AdMob"],
  ["Web Development", "ウェブ開発"],
  ["Digital Marketing", "デジタルマーケティング"],
  ["Marketing", "マーケティング"],
  ["Customer Relationship Management (CRM)", "顧客関係管理(CRM)"],
  ["UI & UX Design", "UI & UXデザイン"],
  ["User Interface (UI) Design", "ユーザーインターフェース(UI)デザイン"],
  ["User Experience (UX) Design", "ユーザーエクスペリエンス(UX)デザイン"],
  ["Business Development", "ビジネス開発"],
  ["Corporate Social Responsibility (CSR)", "企業の社会的責任"],
  ["Graphic Design", "グラフィックデザイン"],
  ["Social Media Marketing", "ソーシャルメディアマーケティング"],
  ["Editing", "編集"],
  ["Social Entrepreneurship", "社会起業"],
  ["Photography", "フォトグラフィー"],
  ["Project Management", "プロジェクトマネジメント"],
  ["Event Management", "イベントマネジメント"],
  ["International Development", "国際開発"],
  ["Brand Management", "ブランドマネジメント"],
  ["Statistical Data Analysis", "統計データ分析"],
  ["Quantitative Research", "定量的リサーチ"],
  ["Qualitative Research", "定性的リサーチ"],
  ["Research", "リサーチ"],
  ["Data Modeling", "データモデリング"],
  ["Management", "経営"],
  ["Fundraising", "ファンドレイジング"],
  ["Capacity Building", "キャパシティビルディング"],
  ["Leadership", "リーダーシップ"],
  ["Public Speaking", "パブリックスピーキング"],
  ["Coaching", "コーチング"],
  ["Career Counseling", "キャリアカウンセリング"],
  ["Strategic Partnerships", "戦略的パートナーシップ"],
  ["Advocacy", "アドボカシー"],
  ["Sales", "営業"],
  ["Gamification", "ゲーミフィケーション"],
  ["Financial Analysis", "財務分析"],
  ["Management Consulting", "経営コンサルティング"],
  ["Investment Banking", "投資銀行業務"],
  ["Program Management", "プログラムマネジメント"],
  ["Product Management", "プロダクトマネジメント"],
  ["Microsoft Office", "マイクロソフトオフィス"],
  ["Computer Aided Design (CAD)", "コンピュータ支援設計(CAD)"],
  ["Strategy", "戦略"],
  ["Ansys", "ANSYS"],
  ["CATIA", "CATIA"],
  ["Simulink", "Simulink"],
  ["Bloomberg Terminal", "ブルームバーグ・ターミナル"],
  ["Sustainable Finance", "サステイナブル・ファイナンス"],
  ["Environmental, Social, and Corporate Governance (ESG)", "ESG(環境・社会・ガバナンス)"],
  ["ESG Investing", "ESG投資"],
  ["Responsible Investing", "責任投資"],
  ["Data Analaysis", "データ分析"],
  ["Renewable Energy", "再生可能エネルギー"],
  ["Social Impact Assessment", "社会的影響評価"],
  ["Environmental Impact Assessment", "環境影響評価"],
  ["Sustainability", "サステナビリティ"],
  ["Strategic Communications", "戦略的コミュニケーション"],
  ["Public Relations (PR)", "広報(PR)"],
  ["Diversity & Inclusion", "ダイバーシティ＆インクルージョン"],
  ["Sustainable Development Goals (SDGs)", "持続可能な開発目標(SDGs)"],
  ["Design Thinking", "デザインシンキング"],
  ["Human-Centered Design (HCD)", "人間中心設計(HCD) "],
  ["Climate Change", "気候変動"],
  ["Sustainable Development", "持続可能な開発"],
  ["Adobe Experience Manager (AEM)", "Adobe Experience Manager (AEM)"],
  ["Communication", "コミュニケーション"],
  ["Customer Service", "顧客サービス"],
  ["Training", "トレーニング"],
  ["Research", "リサーチ"],
  ["Negotiation", "交渉"],
  ["Networking", "ネットワーキング"],
  ["Education", "教育"],
  ["Testing", "テスト"],
  ["Writing", "ライティング"],
  ["Advertising", "広告"],
  ["Databases", "データベース"],
  ["Technology", "テクノロジー"],
  ["Finance", "ファイナンス"],
  ["Retail", "小売"],
  ["Accounting", "会計"],
  ["Social Media", "ソーシャルメディア"],
  ["Engineering", "エンジニアリング"],
  ["Problem Solving", "問題解決"],
  ["Marketing Strategy", "マーケティング戦略"],
  ["Recruiting", "採用"],
  ["Order Fulfillment", "オーダーフルフィルメント"],
  ["Corporate Law", "企業法務"],
  ["Human Resources", "人事"],
  ["People Management", "ピープルマネジメント"],
  ["Manufacturing", "製造業"],
  ["Internal Audit", "内部監査"],
  ["Product Development", "製品開発"],
  ["Auditing", "監査"],
  ["Presentations", "ビジネス戦略"],
  ["Construction", "建設"],
  ["Real Estate", "不動産業"],
  ["Sales Management", "セールスマネジメント"],
  ["Team Building", "チームビルディング"],
  ["Healthcare", "ヘルスケア"],
  ["Compliance", "コンプライアンス"],
  ["Legal", "法務"],
  ["Innovation", "イノベーション"],
  ["Mentoring", "メンタリング"],
  ["Commercial Real Estate", "商業用不動産"],
  ["Information Technology (IT)", "情報技術(IT)"],
  ["Process Improvement", "プロセス改善"],
  ["Change Management", "チェンジマネジメント"],
  ["Heavy Equipment", "重機"],
  ["Facilities Management", "ファシリティマネジメント"],
  ["User Acceptance Testing (UAT)", "ユーザーアクセプタンステスト(UAT)"],
  ["Other", "その他"],
  ["Impact Investing", "インパクト投資"]
];

@Injectable()
export class SkillSeeder {
  constructor(@InjectRepository(Skill) readonly repository: Repository<Skill>) {}

  public async seed(): Promise<void> {
    for (const [en, ja] of skills) {
      await this.repository.save({ enUs: en, jaJp: ja });
    }
  }
}
