ALTER TYPE organization_type ADD VALUE 'EDUCATIONAL';
ALTER TYPE organization_type ADD VALUE 'HEALTHCARE';
ALTER TYPE organization_type ADD VALUE 'RELIGIOUS';
ALTER TYPE organization_type ADD VALUE 'COMMERCIAL';
