

ALTER TYPE notification_type ADD VALUE 'REFERRAL_JOINED';
ALTER TYPE notification_type ADD VALUE 'REFERRAL_VERIFIED';
ALTER TYPE notification_type ADD VALUE 'REFERRAL_HIRED';
ALTER TYPE notification_type ADD VALUE 'REFERRAL_HIRED';
ALTER TYPE notification_type ADD VALUE 'REFERRAL_COMPLETED_JOB';
ALTER TYPE notification_type ADD VALUE 'REFERRAL_CONFIRMED_JOB';

ALTER TYPE notification_type ADD VALUE 'EXPERIENCE_VERIFY_REQUEST';
ALTER TYPE notification_type ADD VALUE 'EXPERIENCE_VERIFY_APPROVED';
ALTER TYPE notification_type ADD VALUE 'EXPERIENCE_VERIFY_REJECTED';

ALTER TYPE notification_type ADD VALUE 'EXPERIENCE_ISSUED';
ALTER TYPE notification_type ADD VALUE 'EXPERIENCE_ISSUED_APPROVED';
ALTER TYPE notification_type ADD VALUE 'EXPERIENCE_ISSUED_REJECTED';
