ALTER TYPE notification_type ADD VALUE 'EDUCATION_VERIFY_REQUEST';
ALTER TYPE notification_type ADD VALUE 'EDUCATION_VERIFY_APPROVED';
ALTER TYPE notification_type ADD VALUE 'EDUCATION_VERIFY_REJECTED';

ALTER TYPE notification_type ADD VALUE 'EDUCATION_ISSUED';
ALTER TYPE notification_type ADD VALUE 'EDUCATION_ISSUED_APPROVED';
ALTER TYPE notification_type ADD VALUE 'EDUCATION_ISSUED_REJECTED';
