ALTER TYPE notification_type
ADD
  VALUE 'DISPUTE_JUROR_SELECTION_COMPLETED_TO_JURORS';

ALTER TYPE notification_type
ADD
  VALUE 'DISPUTE_JUROR_SELECTION_COMPLETED_TO_PARTIES';

ALTER TYPE notification_type
ADD
  VALUE 'DISPUTE_CLOSED_TO_LOSER_PARTY';

ALTER TABLE
  disputes
ADD
  COLUMN winner_party text DEFAULT NULL;
