export const Categories = [
  'SCOPE_AND_CONTRACT_DISPUTES_ISSUES',
  'INCOMPLETE_OR_UNSATISFACTORY_WORK',
  'COMMUNICATION_PROBLEMS',
  'SCOPE_AND_CONTRACT_DISPUTES',
  'INTELLECTUAL_PROPERTY_AND_CONFIDENTIALITY',
  'PROFESSIONALISM_AND_CONDUCT',
  'CANCELLATION_AND_REFUNDS',
  'OTHERS'
]
